-- Update province names in Thai
UPDATE "Province" SET "provinceNameTh" = 'กรุงเทพมหานคร' WHERE "provinceNameEn" = 'Bangkok';
UPDATE "Province" SET "provinceNameTh" = 'อำนาจเจริญ' WHERE "provinceNameEn" = 'Amnat Charoen';
UPDATE "Province" SET "provinceNameTh" = 'อ่างทอง' WHERE "provinceNameEn" = 'Ang Thong';
UPDATE "Province" SET "provinceNameTh" = 'บึงกาฬ' WHERE "provinceNameEn" = 'Bueng Kan';
UPDATE "Province" SET "provinceNameTh" = 'บุรีรัมย์' WHERE "provinceNameEn" = 'Buri Ram';
UPDATE "Province" SET "provinceNameTh" = 'ฉะเชิงเทรา' WHERE "provinceNameEn" = 'Chachoengsao';
UPDATE "Province" SET "provinceNameTh" = 'ชัยนาท' WHERE "provinceNameEn" = 'Chai Nat';
UPDATE "Province" SET "provinceNameTh" = 'ชัยภูมิ' WHERE "provinceNameEn" = 'Chaiyaphum';
UPDATE "Province" SET "provinceNameTh" = 'จันทบุรี' WHERE "provinceNameEn" = 'Chanthaburi';
UPDATE "Province" SET "provinceNameTh" = 'เชียงใหม่' WHERE "provinceNameEn" = 'Chiang Mai';
UPDATE "Province" SET "provinceNameTh" = 'เชียงราย' WHERE "provinceNameEn" = 'Chiang Rai';
UPDATE "Province" SET "provinceNameTh" = 'ชลบุรี' WHERE "provinceNameEn" = 'Chon Buri';
UPDATE "Province" SET "provinceNameTh" = 'ชุมพร' WHERE "provinceNameEn" = 'Chumphon';
UPDATE "Province" SET "provinceNameTh" = 'กาฬสินธุ์' WHERE "provinceNameEn" = 'Kalasin';
UPDATE "Province" SET "provinceNameTh" = 'กำแพงเพชร' WHERE "provinceNameEn" = 'Kamphaeng Phet';
UPDATE "Province" SET "provinceNameTh" = 'กาญจนบุรี' WHERE "provinceNameEn" = 'Kanchanaburi';
UPDATE "Province" SET "provinceNameTh" = 'ขอนแก่น' WHERE "provinceNameEn" = 'Khon Kaen';
UPDATE "Province" SET "provinceNameTh" = 'กระบี่' WHERE "provinceNameEn" = 'Krabi';
UPDATE "Province" SET "provinceNameTh" = 'ลำปาง' WHERE "provinceNameEn" = 'Lampang';
UPDATE "Province" SET "provinceNameTh" = 'ลำพูน' WHERE "provinceNameEn" = 'Lamphun';
UPDATE "Province" SET "provinceNameTh" = 'เลย' WHERE "provinceNameEn" = 'Loei';
UPDATE "Province" SET "provinceNameTh" = 'ลพบุรี' WHERE "provinceNameEn" = 'Lop Buri';
UPDATE "Province" SET "provinceNameTh" = 'แม่ฮ่องสอน' WHERE "provinceNameEn" = 'Mae Hong Son';
UPDATE "Province" SET "provinceNameTh" = 'มหาสารคาม' WHERE "provinceNameEn" = 'Maha Sarakham';
UPDATE "Province" SET "provinceNameTh" = 'มุกดาหาร' WHERE "provinceNameEn" = 'Mukdahan';
UPDATE "Province" SET "provinceNameTh" = 'นครนายก' WHERE "provinceNameEn" = 'Nakhon Nayok';
UPDATE "Province" SET "provinceNameTh" = 'นครปฐม' WHERE "provinceNameEn" = 'Nakhon Pathom';
UPDATE "Province" SET "provinceNameTh" = 'นครพนม' WHERE "provinceNameEn" = 'Nakhon Phanom';
UPDATE "Province" SET "provinceNameTh" = 'นครราชสีมา' WHERE "provinceNameEn" = 'Nakhon Ratchasima';
UPDATE "Province" SET "provinceNameTh" = 'นครสวรรค์' WHERE "provinceNameEn" = 'Nakhon Sawan';
UPDATE "Province" SET "provinceNameTh" = 'นครศรีธรรมราช' WHERE "provinceNameEn" = 'Nakhon Si Thammarat';
UPDATE "Province" SET "provinceNameTh" = 'น่าน' WHERE "provinceNameEn" = 'Nan';
UPDATE "Province" SET "provinceNameTh" = 'นราธิวาส' WHERE "provinceNameEn" = 'Narathiwat';
UPDATE "Province" SET "provinceNameTh" = 'หนองบัวลำภู' WHERE "provinceNameEn" = 'Nong Bua Lam Phu';
UPDATE "Province" SET "provinceNameTh" = 'หนองคาย' WHERE "provinceNameEn" = 'Nong Khai';
UPDATE "Province" SET "provinceNameTh" = 'นนทบุรี' WHERE "provinceNameEn" = 'Nonthaburi';
UPDATE "Province" SET "provinceNameTh" = 'ปทุมธานี' WHERE "provinceNameEn" = 'Pathum Thani';
UPDATE "Province" SET "provinceNameTh" = 'ปัตตานี' WHERE "provinceNameEn" = 'Pattani';
UPDATE "Province" SET "provinceNameTh" = 'พังงา' WHERE "provinceNameEn" = 'Phangnga';
UPDATE "Province" SET "provinceNameTh" = 'พัทลุง' WHERE "provinceNameEn" = 'Phatthalung';
UPDATE "Province" SET "provinceNameTh" = 'พะเยา' WHERE "provinceNameEn" = 'Phayao';
UPDATE "Province" SET "provinceNameTh" = 'เพชรบูรณ์' WHERE "provinceNameEn" = 'Phetchabun';
UPDATE "Province" SET "provinceNameTh" = 'เพชรบุรี' WHERE "provinceNameEn" = 'Phetchaburi';
UPDATE "Province" SET "provinceNameTh" = 'พิจิตร' WHERE "provinceNameEn" = 'Phichit';
UPDATE "Province" SET "provinceNameTh" = 'พิษณุโลก' WHERE "provinceNameEn" = 'Phitsanulok';
UPDATE "Province" SET "provinceNameTh" = 'พระนครศรีอยุธยา' WHERE "provinceNameEn" = 'Phra Nakhon Si Ayutthaya';
UPDATE "Province" SET "provinceNameTh" = 'แพร่' WHERE "provinceNameEn" = 'Phrae';
UPDATE "Province" SET "provinceNameTh" = 'ภูเก็ต' WHERE "provinceNameEn" = 'Phuket';
UPDATE "Province" SET "provinceNameTh" = 'ปราจีนบุรี' WHERE "provinceNameEn" = 'Prachin Buri';
UPDATE "Province" SET "provinceNameTh" = 'ประจวบคีรีขันธ์' WHERE "provinceNameEn" = 'Prachuap Khiri Khan';
UPDATE "Province" SET "provinceNameTh" = 'ระนอง' WHERE "provinceNameEn" = 'Ranong';
UPDATE "Province" SET "provinceNameTh" = 'ราชบุรี' WHERE "provinceNameEn" = 'Ratchaburi';
UPDATE "Province" SET "provinceNameTh" = 'ระยอง' WHERE "provinceNameEn" = 'Rayong';
UPDATE "Province" SET "provinceNameTh" = 'ร้อยเอ็ด' WHERE "provinceNameEn" = 'Roi Et';
UPDATE "Province" SET "provinceNameTh" = 'สระแก้ว' WHERE "provinceNameEn" = 'Sa Kaeo';
UPDATE "Province" SET "provinceNameTh" = 'สกลนคร' WHERE "provinceNameEn" = 'Sakon Nakhon';
UPDATE "Province" SET "provinceNameTh" = 'สมุทรปราการ' WHERE "provinceNameEn" = 'Samut Prakan';
UPDATE "Province" SET "provinceNameTh" = 'สมุทรสาคร' WHERE "provinceNameEn" = 'Samut Sakhon';
UPDATE "Province" SET "provinceNameTh" = 'สมุทรสงคราม' WHERE "provinceNameEn" = 'Samut Songkhram';
UPDATE "Province" SET "provinceNameTh" = 'สระบุรี' WHERE "provinceNameEn" = 'Saraburi';
UPDATE "Province" SET "provinceNameTh" = 'สตูล' WHERE "provinceNameEn" = 'Satun';
UPDATE "Province" SET "provinceNameTh" = 'สิงห์บุรี' WHERE "provinceNameEn" = 'Sing Buri';
UPDATE "Province" SET "provinceNameTh" = 'ศรีสะเกษ' WHERE "provinceNameEn" = 'Sisaket';
UPDATE "Province" SET "provinceNameTh" = 'สงขลา' WHERE "provinceNameEn" = 'Songkhla';
UPDATE "Province" SET "provinceNameTh" = 'สุโขทัย' WHERE "provinceNameEn" = 'Sukhothai';
UPDATE "Province" SET "provinceNameTh" = 'สุพรรณบุรี' WHERE "provinceNameEn" = 'Suphan Buri';
UPDATE "Province" SET "provinceNameTh" = 'สุราษฎร์ธานี' WHERE "provinceNameEn" = 'Surat Thani';
UPDATE "Province" SET "provinceNameTh" = 'สุรินทร์' WHERE "provinceNameEn" = 'Surin';
UPDATE "Province" SET "provinceNameTh" = 'ตาก' WHERE "provinceNameEn" = 'Tak';
UPDATE "Province" SET "provinceNameTh" = 'ตรัง' WHERE "provinceNameEn" = 'Trang';
UPDATE "Province" SET "provinceNameTh" = 'ตราด' WHERE "provinceNameEn" = 'Trat';
UPDATE "Province" SET "provinceNameTh" = 'อุบลราชธานี' WHERE "provinceNameEn" = 'Ubon Ratchathani';
UPDATE "Province" SET "provinceNameTh" = 'อุดรธานี' WHERE "provinceNameEn" = 'Udon Thani';
UPDATE "Province" SET "provinceNameTh" = 'อุทัยธานี' WHERE "provinceNameEn" = 'Uthai Thani';
UPDATE "Province" SET "provinceNameTh" = 'อุตรดิตถ์' WHERE "provinceNameEn" = 'Uttaradit';
UPDATE "Province" SET "provinceNameTh" = 'ยะลา' WHERE "provinceNameEn" = 'Yala';
UPDATE "Province" SET "provinceNameTh" = 'ยโสธร' WHERE "provinceNameEn" = 'Yasothon';
